version: '3.3'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_NAME: meme
      WORDPRESS_DB_USER: mysql_user
      WORDPRESS_DB_PASSWORD: mysql_pw
    working_dir: /var/www/html
    volumes:
      - ./public:/var/www/html

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_pw
      MYSQL_DATABASE: meme
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_pw
    working_dir: /home
    volumes:
      - ./db-data:/home
